src/Entity/Session.php
<?php

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use App\Repository\SessionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
use ApiPlatform\Metadata\Post;
use App\State\SessionStateProcessor;

#[ORM\Entity(repositoryClass: SessionRepository::class)]
#[ApiResource(
    operations:[
        new Post(processor: SessionStateProcessor::class, validationContext: ['groups' => ['Default', 'session:create']]),
    ],
    normalizationContext: ['groups' => ['user:read']],
    denormalizationContext: ['groups' => ['user:create', 'user:update']],
)]
class Session
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?string $date_time = null;

    #[ORM\ManyToOne(inversedBy: 'sessions')]
    private ?Users $users = null;

    /**
     * @var Collection<int, Inform>
     */
    #[ORM\OneToMany(targetEntity: Inform::class, mappedBy: 'session')]
    private Collection $informs;

    public function __construct()
    {
        $this->informs = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateTime(): ?string
    {
        return $this->date_time;
    }

    public function setDateTime(string $date_time ): static
    {
        $this->date_time = $date_time;

        return $this;
    }

    public function getUsers(): ?Users
    {
        return $this->users;
    }

    public function setUsers(?Users $users): static
    {
        $this->users = $users;

        return $this;
    }

    /**
     * @return Collection<int, Inform>
     */
    public function getInforms(): Collection
    {
        return $this->informs;
    }

    public function addInform(Inform $inform): static
    {
        if (!$this->informs->contains($inform)) {
            $this->informs->add($inform);
            $inform->setSession($this);
        }

        return $this;
    }

    public function removeInform(Inform $inform): static
    {
        if ($this->informs->removeElement($inform)) {
            // set the owning side to null (unless already changed)
            if ($inform->getSession() === $this) {
                $inform->setSession(null);
            }
        }

        return $this;
    }
}

src/Controller/ProfileController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Bundle\SecurityBundle\Security;


class ProfileController extends AbstractController
{
    public function __construct(
        private Security $security)
    {
    }

    #[Route('/profile', name: 'app_profile')]
    public function index(): Response
    {
        $user = $this->security->getUser();

        if (!$user)
            return $this->redirectToRoute('app_login');

        $sessionData = [];

        $sessions = $user->getSessions()->toArray();

        foreach (array_reverse($sessions) as $session) {

            $sessionData[] = [
                'date' => $session->getDateTime(),
                'informs' => $session->getInforms()->toArray(), 
            ];
        }


        return $this->render('profile/index.html.twig', [
            'controller_name' => 'ProfileController',
            'email' =>$user->getEmail(),
            'sessions' => $sessionData,
        ]);
    }
}

templates/profile/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Профиль{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>
<div class="example-wrapper">
    <h1>Профиль</h1>
    <p>Email: {{ email }}</p>

    <h2>Сессии:</h2>

    <ul>
        {% for session in sessions %}
            <li>
                Сессия ID: {{ session.date|date("Y-m-d H:i:s") }}
                <canvas id="chart-{{ loop.index }}"></canvas>
                <script>
                    (function() {
                        const ctx = document.getElementById('chart-{{ loop.index }}').getContext('2d');

                        const alphaData = [];
                        const betaData = [];
                        const labels = [];
                        {% for inform in session.informs %}
                            alphaData.push({{ inform.alpha|json_encode|raw }});
                            betaData.push({{ inform.betta|json_encode|raw }});
                            labels.push('{{ inform.dateTime|date("Y-m-d H:i:s") }}');
                        {% endfor %}

                        const myChart = new Chart(ctx, {
                            type: 'line',
                            data: {
                                labels: labels, 
                                datasets: [{
                                    label: 'Alpha',
                                    data: alphaData,
                                    borderColor: 'rgba(255, 99, 132, 1)',
                                    borderWidth: 2,
                                    fill: false
                                },
                                {
                                    label: 'Beta',
                                    data: betaData,
                                    borderColor: 'rgba(54, 162, 235, 1)',
                                    borderWidth: 2,
                                    fill: false
                                }]
                            },
                            options: {
                                scales: {
                                    y: {
                                        beginAtZero: true
                                    }
                                }
                            }
                        });

                    })();
                </script>
            </li>
        {% endfor %}
    </ul>
</div>

{% endblock %}